name: Linting
on:
  pull_request:
    branches: [latest]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.4.0
      with:
        # Optional
        styles: |
          https://github.com/errata-ai/Google/archive/refs/heads/master.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

        # Optional
        config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.VALE_TOKEN}}